### ISSUE TITLE
Can't run the node with rocksdb

### ISSUE THREAD

**Issue by alexqrid** [crypto-org-chain/cronos#1297]
**Describe the bug**
I downloaded rocksdb full archive snapshot from https://quicksync.io/networks/cronos.html
And tried to run the node using the following docker image:
<details><summary>Dockerfile</summary>

```dockerfile
FROM golang:1.20-bullseye

ARG VERSION=1.0.15
WORKDIR /src
RUN apt update && apt install -y wget ca-certificates gcc git make build-essential git curl libsnappy-dev zlib1g-dev libbz2-dev libgflags-dev cmake libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev \
	&&  git clone --depth 1 --branch v8.1.1 https://github.com/facebook/rocksdb.git \
	&&     cd rocksdb && mkdir build && cd build \
	&& cmake .. && cd .. &&  make -j 32 shared_lib && make -j 32 install-shared INSTALL_PATH=/usr
RUN git clone https://github.com/crypto-org-chain/cronos.git \
	&& cd cronos \
	&& git checkout v${VERSION} \
    && COSMOS_BUILD_OPTIONS=rocksdb make install
ENTRYPOINT ["cronosd", "start"]

```
</details>

I've set container limits to 16 CPU and 256Gib RAM.
But the node fails with out of memory errors.
Paste the full stack trace at pastebin - https://pastebin.com/dxPYBmAJ

**Expected behavior**
Node runs and syncs

**Additional context**
My server has 1TB RAM, may be the container tries to utilize it fully and fails due to `256Gib` memory limits I put?

**Comment by alexqrid** [comment]
Attaching compose file I am using to run the node
```yaml
version: "3.5"
networks:
  default:
    name: cronos

volumes:
  cronos-snap:
    driver: local
    driver_opts:
      type: none
      device: /home/cronos/.data
      o: bind
  cronos-config:
    driver: local
    driver_opts:
      type: none
      device: /home/cronos/node/config
      o: bind

x-logging: &logging
  logging:
    driver: json-file
    options:
      max-size: 5m
      max-file: "2"

services:
  cronos-node:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VERSION=$TAG
    image: cronos:$TAG
    restart: always
    <<: *logging
    volumes:
      - cronos-snap:/home/cronos/data
      - cronos-config:/home/cronos/config
    environment:
      - LD_LIBRARY_PATH=/src/rocksdb
      - CPLUS_INCLUDE_PATH=/src/rocksdb/include
    deploy:
      resources:
        limits:
          memory: 256G
          cpus: "16"
        reservations:
          memory: 8G
          cpus: "4"
    command:
      - --home
      - /home/cronos/
      - --trace
      - --log_level
      - trace
      - --log_format
      - json
```
