### ISSUE TITLE
Metamask does not guess the currency symbol && Not Metamask connection (Solved) && Problem following https://docs.cronos.org/for-node-hosts/running-nodes/local-devnet: gas prices; got: 0 required: 7: insufficient fee (Solved)

### ISSUE THREAD

**Issue by EAG-es** [crypto-org-chain/cronos#1321]
I am following [https://docs.cronos.org/for-node-hosts/running-nodes/local-devnet](https://docs.cronos.org/for-node-hosts/running-nodes/local-devnet)

**Option 2**
```
Modify the configuration script: ./scripts/cronos-devnet.yaml 
```
**Use pystarport**
```
pystarport serve --config ./scripts/cronos-devnet.yaml 
the serve command would truncate all the blocks previously generated and regenerate a new genesis block, which means you'll also lose all of your transaction records. 
the accounts' information is generated in: data/cronos_777-1/accounts.json
If you wish to restart the chain with the existing blocks, please run pystarport with start command:
pystarport start --config ./scripts/cronos-devnet.yaml
```
**Operations**
**Key management**
```
cronosd keys add signer2 --recover --keyring-backend test
(The bip39 mnemonic, as can be found in data/cronos_777-1/accounts.json, in “mnemonic” field)
{"name": "signer2", "type": "local", "address": "crc1q04jewhxw4xxu3vlg3rc85240h9q7ns6hglz0g", "pubkey": "{\"@type\":\"/ethermint.crypto.v1.ethsecp256k1.PubKey\",\"key\":\"A3K9+A9hnuhqkxn+/GHLVZwFthvAERmvpSupb0d44WtD\"}", "mnemonic": "night renew tonight dinner shaft scheme domain oppose echo summer broccoli agent face guitar surface belt veteran siren poem alcohol menu custom crunch index"}
```
**See balance**
```
sudo apt install jq
cronosd q bank balances crc1q04jewhxw4xxu3vlg3rc85240h9q7ns6hglz0g -o json | jq
  {
  "balances": [
    {
      "denom": "basetcro",
      "amount": "30000000000000000000000"
    }
  ],
  "pagination": {
    "next_key": null,
    "total": "0"
  }
}
```
**Transfer token to another address**
```
cronosd keys add Bob --keyring-backend test

- address: crc1jyylfq5wq8dg7shyz8chgyl7tv37z02qq43ms2
  name: Bob
  pubkey: '{"@type":"/ethermint.crypto.v1.ethsecp256k1.PubKey","key":"AgsFPVdkEm0CM1sWibpvng7gAv+Z7t9ZbcOdVxbqiK11"}'
  type: local

**Important** write this mnemonic phrase in a safe place.

It is the only way to recover your account if you ever forget your password.

dash similar old grief extra duty cost hotel tray balcony foam together episode inject pride ramp dash bundle chalk real subject trick negative despair
```
**Now we can transfer tokens to Bob, for example you can send 1basetcro to Bob's address by**
```
cronosd tx bank send signer2 crc1jyylfq5wq8dg7shyz8chgyl7tv37z02qq43ms2 1basetcro --keyring-backend test --chain-id cronos_777-1
auth_info:
  fee:
    amount: []
    gas_limit: "200000"
    granter: ""
    payer: ""
  signer_infos: []
  tip: null
body:
  extension_options: []
  memo: ""
  messages:
  - '@type': /cosmos.bank.v1beta1.MsgSend
    amount:
    - amount: "1"
      denom: basetcro
    from_address: crc1q04jewhxw4xxu3vlg3rc85240h9q7ns6hglz0g
    to_address: crc1jyylfq5wq8dg7shyz8chgyl7tv37z02qq43ms2
  non_critical_extension_options: []
  timeout_height: "0"
signatures: []
confirm transaction before signing and broadcasting [y/N]: y
…
```
`#FF0000`  **Error:** 
### gas prices; got: 0 required: 7: insufficient fee"

`#00FF00` **Questions:**
### Why does not have funds to pay transactions but has funds (30000000000000000000000 basetcro)?
Thanks for your support.
